server:
  port: 8081

spring:
  appication:
    name: account
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    username: deezzex
    url: jdbc:postgresql://localhost:5432/account
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true