server:
  port: 8082

spring:
  appication:
    name: ACCOUNT-SERVICE
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    username: deezzex
    url: jdbc:postgresql://localhost:5432/account
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost