server:
  port: 8082

spring:
  application:
    name: ACCOUNT-SERVICE
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    username: deezzex
    url: jdbc:postgresql://localhost:5432/account
    password: password
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
