server:
  port: 8080

spring:
  appication:
    name: CUSTOMER-SERVICE
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    username: deezzex
    url: jdbc:postgresql://localhost:5432/customer
    password: password
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  registration:
    enabled: false




