server:
  port: 8080

spring:
  application:
    name: CUSTOMER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/zipkin/
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    username: deezzex
    url: jdbc:postgresql://localhost:5432/customer
    password: password
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true





