server:
  port: 8888

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**

  main:
    web-application-type: reactive