server:
  port: 8999

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/deezzex/config-server
          clone-on-start: true
